/**
 * data.js - Dados iniciais fictícios para primeiro carregamento
 * Caso o localStorage esteja vazio, esses dados serão carregados para demonstração.
 */

// Gera datas relativas para manter os status realistas independente da data de teste
function getRelativeDate(daysOffset) {
    const d = new Date();
    d.setDate(d.getDate() + daysOffset);
    return d.toISOString().split('T')[0];
}

const initialComputers = [
    {
        id: "pc-001",
        nome: "Lucas",
        ip: "192.168.5.1",
        mac: "1C-C1-DE-A2-43-B3",
        ativo: "001-0102",
        setor: "Recebimento",
        responsavel: "Lucas",
        ultimaLimpeza: "",
        proximaLimpeza: "2026-10-05",
        preventiva: "05/10",
        statusPlanilha: "Pendente",
        problemaEncontrado: "",
        solucaoAcao: "",
        observacoes: ""
    },
    {
        id: "pc-002",
        nome: "Almoxarifado",
        ip: "192.168.5.175",
        mac: "44-BA-DB-06-46-CC",
        ativo: "001-0103",
        setor: "Almoxarifado",
        responsavel: "Almoxarifado",
        ultimaLimpeza: "",
        proximaLimpeza: "2026-10-05",
        preventiva: "05/10",
        statusPlanilha: "Pendente",
        problemaEncontrado: "",
        solucaoAcao: "",
        observacoes: ""
    },
    {
        id: "pc-003",
        nome: "Liedson",
        ip: "192.168.5.172",
        mac: "44-BA-DB-06-46-CC",
        ativo: "001-0104",
        setor: "Almoxarifado",
        responsavel: "Liedson",
        ultimaLimpeza: "",
        proximaLimpeza: "2026-10-05",
        preventiva: "05/10",
        statusPlanilha: "Pendente",
        problemaEncontrado: "",
        solucaoAcao: "",
        observacoes: ""
    },
    {
        id: "pc-004",
        nome: "Ewerton",
        ip: "192.168.5.108",
        mac: "78-28-CB-BD-DA-B7",
        ativo: "001-0105",
        setor: "Almoxarifado",
        responsavel: "Ewerton",
        ultimaLimpeza: "",
        proximaLimpeza: "2026-10-05",
        preventiva: "05/10",
        statusPlanilha: "Pendente",
        problemaEncontrado: "",
        solucaoAcao: "",
        observacoes: ""
    },
    {
        id: "pc-005",
        nome: "Amanda",
        ip: "192.168.5.165",
        mac: "47-47-FE-3C",
        ativo: "001-0106",
        setor: "Almoxarifado",
        responsavel: "Amanda",
        ultimaLimpeza: "",
        proximaLimpeza: "2026-10-05",
        preventiva: "05/10",
        statusPlanilha: "Pendente",
        problemaEncontrado: "",
        solucaoAcao: "",
        observacoes: ""
    },
    {
        id: "pc-006",
        nome: "Carlos Reina",
        ip: "192.168.5.164",
        mac: "F4-8E-38-DF-91-41",
        ativo: "001-0107",
        setor: "Almoxarifado",
        responsavel: "Carlos Reina",
        ultimaLimpeza: "",
        proximaLimpeza: "2026-10-05",
        preventiva: "05/10",
        statusPlanilha: "Pendente",
        problemaEncontrado: "",
        solucaoAcao: "",
        observacoes: ""
    },
    {
        id: "pc-007",
        nome: "Maximino Nunes",
        ip: "192.168.4.191",
        mac: "5C-C9-30-D3-01-A4",
        ativo: "001-0108",
        setor: "Almoxarifado",
        responsavel: "Maximino Nunes",
        ultimaLimpeza: "",
        proximaLimpeza: "2026-10-06",
        preventiva: "06/10",
        statusPlanilha: "Pendente",
        problemaEncontrado: "",
        solucaoAcao: "",
        observacoes: ""
    },
    {
        id: "pc-008",
        nome: "Rosana",
        ip: "192.168.5.49",
        mac: "18-A9-9B-FE-D5-EE",
        ativo: "001-0110",
        setor: "Portaria",
        responsavel: "Rosana",
        ultimaLimpeza: "",
        proximaLimpeza: "2026-10-06",
        preventiva: "06/10",
        statusPlanilha: "Pendente",
        problemaEncontrado: "",
        solucaoAcao: "",
        observacoes: ""
    },
    {
        id: "pc-009",
        nome: "Joice",
        ip: "192.168.5.50",
        mac: "5C-F9-DD-EB-12-93",
        ativo: "001-0111",
        setor: "Fiscal",
        responsavel: "Joice",
        ultimaLimpeza: "",
        proximaLimpeza: "2026-10-06",
        preventiva: "06/10",
        statusPlanilha: "Pendente",
        problemaEncontrado: "",
        solucaoAcao: "",
        observacoes: ""
    },
    {
        id: "pc-010",
        nome: "Graziela",
        ip: "192.168.5.132",
        mac: "78-2B-CB-BD-B6-15",
        ativo: "001-0112",
        setor: "Fiscal",
        responsavel: "Graziela",
        ultimaLimpeza: "",
        proximaLimpeza: "2026-10-06",
        preventiva: "06/10",
        statusPlanilha: "Pendente",
        problemaEncontrado: "",
        solucaoAcao: "",
        observacoes: ""
    },
    {
        id: "pc-011",
        nome: "Antonia",
        ip: "192.168.5.159",
        mac: "74-86-8A-F7-0F-E3",
        ativo: "001-0113",
        setor: "Fiscal",
        responsavel: "Antonia",
        ultimaLimpeza: "",
        proximaLimpeza: "2026-10-06",
        preventiva: "06/10",
        statusPlanilha: "Pendente",
        problemaEncontrado: "",
        solucaoAcao: "",
        observacoes: ""
    },
    {
        id: "pc-012",
        nome: "Patricia",
        ip: "192.168.5.127",
        mac: "F0-4D-A2-E4-BE-FB",
        ativo: "001-0114",
        setor: "Fiscal",
        responsavel: "Patricia",
        ultimaLimpeza: "",
        proximaLimpeza: "2026-10-07",
        preventiva: "07/10",
        statusPlanilha: "Pendente",
        problemaEncontrado: "",
        solucaoAcao: "",
        observacoes: ""
    },
    {
        id: "pc-013",
        nome: "Evelyn",
        ip: "192.168.5.166",
        mac: "00-E0-4C-36-3C-AE",
        ativo: "001-0119",
        setor: "Fiscal",
        responsavel: "Evelyn",
        ultimaLimpeza: "",
        proximaLimpeza: "2026-10-07",
        preventiva: "07/10",
        statusPlanilha: "Pendente",
        problemaEncontrado: "",
        solucaoAcao: "",
        observacoes: ""
    },
    {
        id: "pc-014",
        nome: "Miguel",
        ip: "192.168.5.48",
        mac: "5C-F9-DD-EB-12-7F",
        ativo: "001-0115",
        setor: "Compras",
        responsavel: "Miguel",
        ultimaLimpeza: "",
        proximaLimpeza: "2026-10-07",
        preventiva: "07/10",
        statusPlanilha: "Pendente",
        problemaEncontrado: "",
        solucaoAcao: "",
        observacoes: ""
    },
    {
        id: "pc-015",
        nome: "Marcos",
        ip: "192.168.5.135",
        mac: "74-76-7A-F7-0B-75",
        ativo: "001-0116",
        setor: "Compras",
        responsavel: "Marcos",
        ultimaLimpeza: "",
        proximaLimpeza: "2026-10-07",
        preventiva: "07/10",
        statusPlanilha: "Pendente",
        problemaEncontrado: "",
        solucaoAcao: "",
        observacoes: ""
    },
    {
        id: "pc-016",
        nome: "Camila",
        ip: "192.168.5.17",
        mac: "84-7B-EB-E5-49-A8",
        ativo: "001-0117",
        setor: "Compras",
        responsavel: "Camila",
        ultimaLimpeza: "",
        proximaLimpeza: "2026-10-07",
        preventiva: "07/10",
        statusPlanilha: "Pendente",
        problemaEncontrado: "",
        solucaoAcao: "",
        observacoes: ""
    },
    {
        id: "pc-017",
        nome: "Ana Amelia",
        ip: "192.168.5.90",
        mac: "AC-9E-17-DE-F5-A4",
        ativo: "001-0118",
        setor: "Cronoanalista",
        responsavel: "Ana Amelia",
        ultimaLimpeza: "",
        proximaLimpeza: "2026-10-07",
        preventiva: "07/10",
        statusPlanilha: "Pendente",
        problemaEncontrado: "",
        solucaoAcao: "",
        observacoes: ""
    },
    {
        id: "pc-018",
        nome: "Vago",
        ip: "192.168.5.27",
        mac: "00-E0-4C-34-00-88",
        ativo: "001-0120",
        setor: "Engenharia",
        responsavel: "Vago",
        ultimaLimpeza: "",
        proximaLimpeza: "2026-10-08",
        preventiva: "08/10",
        statusPlanilha: "Pendente",
        problemaEncontrado: "",
        solucaoAcao: "",
        observacoes: ""
    },
    {
        id: "pc-019",
        nome: "Davi",
        ip: "192.168.5.158",
        mac: "74-86-7A-FB-58-CF",
        ativo: "001-0121",
        setor: "Engenharia",
        responsavel: "Davi",
        ultimaLimpeza: "",
        proximaLimpeza: "2026-10-08",
        preventiva: "08/10",
        statusPlanilha: "Pendente",
        problemaEncontrado: "",
        solucaoAcao: "",
        observacoes: ""
    },
    {
        id: "pc-020",
        nome: "Vanessa",
        ip: "192.168.5.142",
        mac: "78-2B-CB-C2-F1-C6",
        ativo: "001-0122",
        setor: "Financeiro",
        responsavel: "Vanessa",
        ultimaLimpeza: "",
        proximaLimpeza: "2026-10-08",
        preventiva: "08/10",
        statusPlanilha: "Pendente",
        problemaEncontrado: "",
        solucaoAcao: "",
        observacoes: ""
    },
    {
        id: "pc-021",
        nome: "Chayanne",
        ip: "192.168.5.112",
        mac: "84-7B-EB-E5-68-AB",
        ativo: "001-0123",
        setor: "Financeiro",
        responsavel: "Chayanne",
        ultimaLimpeza: "",
        proximaLimpeza: "2026-10-08",
        preventiva: "08/10",
        statusPlanilha: "Pendente",
        problemaEncontrado: "",
        solucaoAcao: "",
        observacoes: ""
    },
    {
        id: "pc-022",
        nome: "Amanda",
        ip: "192.168.5.117",
        mac: "74-86-7A-F9-40-22",
        ativo: "001-0124",
        setor: "Financeiro",
        responsavel: "Amanda",
        ultimaLimpeza: "",
        proximaLimpeza: "2026-10-08",
        preventiva: "08/10",
        statusPlanilha: "Pendente",
        problemaEncontrado: "",
        solucaoAcao: "",
        observacoes: ""
    },
    {
        id: "pc-023",
        nome: "Deise",
        ip: "192.168.5.110",
        mac: "74-86-7A-F9-40-22",
        ativo: "001-0125",
        setor: "Financeiro",
        responsavel: "Deise",
        ultimaLimpeza: "",
        proximaLimpeza: "2026-10-08",
        preventiva: "08/10",
        statusPlanilha: "Pendente",
        problemaEncontrado: "",
        solucaoAcao: "",
        observacoes: ""
    },
    {
        id: "pc-024",
        nome: "Wellington - Consulta",
        ip: "192.168.5.73",
        mac: "00-23-7D-D5-E3-0A",
        ativo: "001-0126",
        setor: "Transmissão",
        responsavel: "Wellington - Consulta",
        ultimaLimpeza: "",
        proximaLimpeza: "2026-10-09",
        preventiva: "09/10",
        statusPlanilha: "Pendente",
        problemaEncontrado: "",
        solucaoAcao: "",
        observacoes: ""
    },
    {
        id: "pc-025",
        nome: "Wellington",
        ip: "192.168.5.63",
        mac: "54-48-10-FF-42-40",
        ativo: "001-0179",
        setor: "Transmissão",
        responsavel: "Wellington",
        ultimaLimpeza: "",
        proximaLimpeza: "2026-10-09",
        preventiva: "09/10",
        statusPlanilha: "Pendente",
        problemaEncontrado: "",
        solucaoAcao: "",
        observacoes: ""
    },

        {
        id: "pc-026",
        nome: "Vanessa",
        ip: "192.168.5.123",
        mac: "F0-4D-A2-E7-3E-B4",
        ativo: "001-0127",
        setor: "Manutenção",
        responsavel: "Vanessa",
        ultimaLimpeza: "",
        proximaLimpeza: "2026-10-09",
        preventiva: "09/10",
        statusPlanilha: "Pendente",
        problemaEncontrado: "",
        solucaoAcao: "",
        observacoes: ""
    },
    {
        id: "pc-027",
        nome: "Daiane",
        ip: "192.168.5.133",
        mac: "D0-8A-8A-6E-73-3C",
        ativo: "001-0129",
        setor: "ADM",
        responsavel: "Daiane",
        ultimaLimpeza: "",
        proximaLimpeza: "2026-10-09",
        preventiva: "09/10",
        statusPlanilha: "Pendente",
        problemaEncontrado: "",
        solucaoAcao: "",
        observacoes: ""
    },
    {
        id: "pc-028",
        nome: "Micheli",
        ip: "192.168.7.41",
        mac: "F0-4D-A2-E5-13-13",
        ativo: "001-0178",
        setor: "Financeiro Log Parts",
        responsavel: "Micheli",
        ultimaLimpeza: "",
        proximaLimpeza: "2026-10-12",
        preventiva: "12/10",
        statusPlanilha: "Pendente",
        problemaEncontrado: "",
        solucaoAcao: "",
        observacoes: ""
    },
    {
        id: "pc-029",
        nome: "Valdecir",
        ip: "192.168.5.43",
        mac: "18-03-73-3E-62-78",
        ativo: "001-0131",
        setor: "Expedição Log",
        responsavel: "Valdecir",
        ultimaLimpeza: "",
        proximaLimpeza: "2026-10-12",
        preventiva: "12/10",
        statusPlanilha: "Pendente",
        problemaEncontrado: "",
        solucaoAcao: "",
        observacoes: ""
    },
    {
        id: "pc-030",
        nome: "Geisiel",
        ip: "192.168.7.24",
        mac: "1C-C1-DE-2A-53-5C",
        ativo: "001-0132",
        setor: "Expedição Log",
        responsavel: "Geisiel",
        ultimaLimpeza: "",
        proximaLimpeza: "2026-10-12",
        preventiva: "12/10",
        statusPlanilha: "Pendente",
        problemaEncontrado: "",
        solucaoAcao: "",
        observacoes: ""
    },
    {
        id: "pc-031",
        nome: "Angela",
        ip: "192.168.7.44",
        mac: "00-E0-4B-41-2F-3A",
        ativo: "001-0133",
        setor: "Gerente Log",
        responsavel: "Angela",
        ultimaLimpeza: "",
        proximaLimpeza: "2026-10-12",
        preventiva: "12/10",
        statusPlanilha: "Pendente",
        problemaEncontrado: "",
        solucaoAcao: "",
        observacoes: ""
    },
    {
        id: "pc-032",
        nome: "Tamires",
        ip: "192.168.7.34",
        mac: "74-86-7A-FD-02-68",
        ativo: "001-0134",
        setor: "Exportação e Importação",
        responsavel: "Tamires",
        ultimaLimpeza: "",
        proximaLimpeza: "2026-10-12",
        preventiva: "12/10",
        statusPlanilha: "Pendente",
        problemaEncontrado: "",
        solucaoAcao: "",
        observacoes: ""
    },
    {
        id: "pc-033",
        nome: "Laís",
        ip: "192.168.7.29",
        mac: "78-2B-CB-C2-98-B4",
        ativo: "001-0135",
        setor: "Comercial",
        responsavel: "Laís",
        ultimaLimpeza: "",
        proximaLimpeza: "2026-10-13",
        preventiva: "13/10",
        statusPlanilha: "Pendente",
        problemaEncontrado: "",
        solucaoAcao: "",
        observacoes: ""
    },
    {
        id: "pc-034",
        nome: "Simone",
        ip: "192.168.7.26",
        mac: "5C-F9-DD-EB-35-10",
        ativo: "001-0136",
        setor: "Comercial",
        responsavel: "Simone",
        ultimaLimpeza: "",
        proximaLimpeza: "2026-10-13",
        preventiva: "13/10",
        statusPlanilha: "Pendente",
        problemaEncontrado: "",
        solucaoAcao: "",
        observacoes: ""
    },
    {
        id: "pc-035",
        nome: "Camila",
        ip: "192.168.7.42",
        mac: "F0-4D-A2-E3-F1-45",
        ativo: "001-0137",
        setor: "Comercial",
        responsavel: "Camila",
        ultimaLimpeza: "",
        proximaLimpeza: "2026-10-13",
        preventiva: "13/10",
        statusPlanilha: "Pendente",
        problemaEncontrado: "",
        solucaoAcao: "",
        observacoes: ""
    },
    {
        id: "pc-036",
        nome: "João",
        ip: "192.168.7.35",
        mac: "90-8A-1C-2F-32-4C",
        ativo: "001-0138",
        setor: "Comercial",
        responsavel: "João",
        ultimaLimpeza: "",
        proximaLimpeza: "2026-10-13",
        preventiva: "13/10",
        statusPlanilha: "Pendente",
        problemaEncontrado: "",
        solucaoAcao: "",
        observacoes: ""
    },
    {
        id: "pc-037",
        nome: "Adão",
        ip: "192.168.7.30",
        mac: "34-E8-D7-FB-D8-83",
        ativo: "001-0139",
        setor: "Comercial",
        responsavel: "Adão",
        ultimaLimpeza: "",
        proximaLimpeza: "2026-10-13",
        preventiva: "13/10",
        statusPlanilha: "Pendente",
        problemaEncontrado: "",
        solucaoAcao: "",
        observacoes: ""
    },
    {
        id: "pc-038",
        nome: "Rayssa",
        ip: "192.168.5.180",
        mac: "74-86-7A-FD-3F-45",
        ativo: "001-0140",
        setor: "Laboratório",
        responsavel: "Rayssa",
        ultimaLimpeza: "",
        proximaLimpeza: "2026-10-13",
        preventiva: "13/10",
        statusPlanilha: "Pendente",
        problemaEncontrado: "",
        solucaoAcao: "",
        observacoes: ""
    },
    {
        id: "pc-039",
        nome: "Gabriele",
        ip: "192.168.5.121",
        mac: "5C-F9-DD-EB-35-F7",
        ativo: "001-0142",
        setor: "Laboratório",
        responsavel: "Gabriele",
        ultimaLimpeza: "",
        proximaLimpeza: "2026-10-14",
        preventiva: "14/10",
        statusPlanilha: "Pendente",
        problemaEncontrado: "",
        solucaoAcao: "",
        observacoes: ""
    },
    {
        id: "pc-040",
        nome: "Camila",
        ip: "192.168.5.168",
        mac: "18-A9-9B-FE-D0-CA",
        ativo: "001-0143",
        setor: "RH",
        responsavel: "Camila",
        ultimaLimpeza: "",
        proximaLimpeza: "2026-10-14",
        preventiva: "14/10",
        statusPlanilha: "Pendente",
        problemaEncontrado: "",
        solucaoAcao: "",
        observacoes: ""
    },
    {
        id: "pc-041",
        nome: "Consulta",
        ip: "192.168.5.41",
        mac: "7C-83-34-BC-0B-08",
        ativo: "001-0144",
        setor: "Meta",
        responsavel: "Consulta",
        ultimaLimpeza: "",
        proximaLimpeza: "2026-10-14",
        preventiva: "14/10",
        statusPlanilha: "Pendente",
        problemaEncontrado: "",
        solucaoAcao: "",
        observacoes: ""
    },
    {
        id: "pc-042",
        nome: "Wilson",
        ip: "192.168.5.174",
        mac: "00-E0-4B-41-38-CC",
        ativo: "001-0145",
        setor: "Meta",
        responsavel: "Wilson",
        ultimaLimpeza: "",
        proximaLimpeza: "2026-10-15",
        preventiva: "15/10",
        statusPlanilha: "Pendente",
        problemaEncontrado: "",
        solucaoAcao: "",
        observacoes: ""
    },
    {
        id: "pc-043",
        nome: "Alessandra",
        ip: "192.168.5.78",
        mac: "5C-F9-DD-EB-7A-28",
        ativo: "001-0146",
        setor: "SAC",
        responsavel: "Alessandra",
        ultimaLimpeza: "",
        proximaLimpeza: "2026-10-15",
        preventiva: "15/10",
        statusPlanilha: "Pendente",
        problemaEncontrado: "",
        solucaoAcao: "",
        observacoes: ""
    },
    {
        id: "pc-044",
        nome: "Sandra",
        ip: "192.168.5.67",
        mac: "78-2B-CB-EB-BA-0B",
        ativo: "001-0147",
        setor: "PCP",
        responsavel: "Sandra",
        ultimaLimpeza: "",
        proximaLimpeza: "2026-10-15",
        preventiva: "15/10",
        statusPlanilha: "Pendente",
        problemaEncontrado: "",
        solucaoAcao: "",
        observacoes: ""
    },
    {
        id: "pc-045",
        nome: "Patricia",
        ip: "192.168.5.100",
        mac: "78-2B-CB-B6-77-E1",
        ativo: "001-0148",
        setor: "PCP",
        responsavel: "Patricia",
        ultimaLimpeza: "",
        proximaLimpeza: "2026-10-15",
        preventiva: "15/10",
        statusPlanilha: "Pendente",
        problemaEncontrado: "",
        solucaoAcao: "",
        observacoes: ""
    },
    {
        id: "pc-046",
        nome: "Leandro",
        ip: "192.168.5.9",
        mac: "",
        ativo: "001-0149",
        setor: "Desmontagem",
        responsavel: "Leandro",
        ultimaLimpeza: "",
        proximaLimpeza: "2026-10-16",
        preventiva: "16/10",
        statusPlanilha: "Pendente",
        problemaEncontrado: "",
        solucaoAcao: "",
        observacoes: ""
    },
    {
        id: "pc-047",
        nome: "Robson-Japão",
        ip: "192.168.5.116",
        mac: "78-2B-CB-E0-30-8F",
        ativo: "001-0150",
        setor: "Desmontagem",
        responsavel: "Robson-Japão",
        ultimaLimpeza: "",
        proximaLimpeza: "2026-10-16",
        preventiva: "16/10",
        statusPlanilha: "Pendente",
        problemaEncontrado: "",
        solucaoAcao: "",
        observacoes: ""
    },
    {
        id: "pc-048",
        nome: "Daiane",
        ip: "192.168.5.108",
        mac: "7C-83-34-AB-EE-14",
        ativo: "001-0151",
        setor: "Desmontagem",
        responsavel: "Daiane",
        ultimaLimpeza: "",
        proximaLimpeza: "2026-10-18",
        preventiva: "18/10",
        statusPlanilha: "Pendente",
        problemaEncontrado: "",
        solucaoAcao: "",
        observacoes: ""
    },
    {
        id: "pc-049",
        nome: "Rodrigo",
        ip: "192.168.5.208",
        mac: "1C-C1-DE-2A-53-38",
        ativo: "001-0152",
        setor: "Desmontagem",
        responsavel: "Rodrigo",
        ultimaLimpeza: "",
        proximaLimpeza: "2026-10-18",
        preventiva: "18/10",
        statusPlanilha: "Pendente",
        problemaEncontrado: "",
        solucaoAcao: "",
        observacoes: ""
    },
    {
        id: "pc-050",
        nome: "David",
        ip: "192.168.5.125",
        mac: "54-48-10-FF-42-40",
        ativo: "001-0153",
        setor: "Desmontagem",
        responsavel: "David",
        ultimaLimpeza: "",
        proximaLimpeza: "2026-10-18",
        preventiva: "18/10",
        statusPlanilha: "Pendente",
        problemaEncontrado: "",
        solucaoAcao: "",
        observacoes: ""
    },
        {
        id: "pc-051",
        nome: "Naiame",
        ip: "192.168.5.190",
        mac: "2C-27-D7-94-75-6C",
        ativo: "001-0154",
        setor: "Desmontagem",
        responsavel: "Naiame",
        ultimaLimpeza: "",
        proximaLimpeza: "2026-10-18",
        preventiva: "18/10",
        statusPlanilha: "Pendente",
        problemaEncontrado: "",
        solucaoAcao: "",
        observacoes: ""
    },
    {
        id: "pc-052",
        nome: "Suelen",
        ip: "192.168.5.20",
        mac: "F0-4D-A2-E5-13-13",
        ativo: "001-0156",
        setor: "Desmontagem",
        responsavel: "Suelen",
        ultimaLimpeza: "",
        proximaLimpeza: "2026-10-18",
        preventiva: "18/10",
        statusPlanilha: "Pendente",
        problemaEncontrado: "",
        solucaoAcao: "",
        observacoes: ""
    },
    {
        id: "pc-053",
        nome: "Victor",
        ip: "192.168.5.74",
        mac: "F8-83-73-3E-62-7B",
        ativo: "001-0157",
        setor: "Desmontagem",
        responsavel: "Victor",
        ultimaLimpeza: "",
        proximaLimpeza: "2026-10-20",
        preventiva: "20/10",
        statusPlanilha: "Pendente",
        problemaEncontrado: "",
        solucaoAcao: "",
        observacoes: ""
    },
    {
        id: "pc-054",
        nome: "Robson",
        ip: "192.168.5.201",
        mac: "84-7B-EB-E5-73-EB",
        ativo: "001-0158",
        setor: "Motor de Partida",
        responsavel: "Robson",
        ultimaLimpeza: "",
        proximaLimpeza: "2026-10-20",
        preventiva: "20/10",
        statusPlanilha: "Pendente",
        problemaEncontrado: "",
        solucaoAcao: "",
        observacoes: ""
    },
    {
        id: "pc-055",
        nome: "Gabriel",
        ip: "192.168.5.160",
        mac: "74-86-7A-F7-10-02",
        ativo: "001-0159",
        setor: "Motor de Partida",
        responsavel: "Gabriel",
        ultimaLimpeza: "",
        proximaLimpeza: "2026-10-20",
        preventiva: "20/10",
        statusPlanilha: "Pendente",
        problemaEncontrado: "",
        solucaoAcao: "",
        observacoes: ""
    },
    {
        id: "pc-056",
        nome: "Ana",
        ip: "192.168.5.37",
        mac: "4A-BA-DB-06-48-5A",
        ativo: "001-0160",
        setor: "Motor de Partida",
        responsavel: "Ana",
        ultimaLimpeza: "",
        proximaLimpeza: "2026-10-21",
        preventiva: "21/10",
        statusPlanilha: "Pendente",
        problemaEncontrado: "",
        solucaoAcao: "",
        observacoes: ""
    },
    {
        id: "pc-057",
        nome: "Junior",
        ip: "192.168.5.101",
        mac: "74-86-7A-FD-38-88",
        ativo: "001-0161",
        setor: "Usinagem",
        responsavel: "Junior",
        ultimaLimpeza: "",
        proximaLimpeza: "2026-10-21",
        preventiva: "21/10",
        statusPlanilha: "Pendente",
        problemaEncontrado: "",
        solucaoAcao: "",
        observacoes: ""
    },
    {
        id: "pc-058",
        nome: "Consulta",
        ip: "192.168.5.63",
        mac: "34-D0-A9-01-F6-22",
        ativo: "001-0162",
        setor: "Usinagem",
        responsavel: "Consulta",
        ultimaLimpeza: "",
        proximaLimpeza: "2026-10-21",
        preventiva: "21/10",
        statusPlanilha: "Pendente",
        problemaEncontrado: "",
        solucaoAcao: "",
        observacoes: ""
    },
    {
        id: "pc-059",
        nome: "Jhonny",
        ip: "192.168.5.160",
        mac: "D4-8B-54-CE-D0-4A",
        ativo: "001-0163",
        setor: "Bobina",
        responsavel: "Jhonny",
        ultimaLimpeza: "",
        proximaLimpeza: "2026-10-21",
        preventiva: "21/10",
        statusPlanilha: "Pendente",
        problemaEncontrado: "",
        solucaoAcao: "",
        observacoes: ""
    },
    {
        id: "pc-060",
        nome: "Consulta",
        ip: "192.168.5.88",
        mac: "34-E8-D7-FB-DB-88",
        ativo: "001-0164",
        setor: "Bobina",
        responsavel: "Consulta",
        ultimaLimpeza: "",
        proximaLimpeza: "2026-10-21",
        preventiva: "21/10",
        statusPlanilha: "Pendente",
        problemaEncontrado: "",
        solucaoAcao: "",
        observacoes: ""
    },
    {
        id: "pc-061",
        nome: "Anthony",
        ip: "192.168.5.48",
        mac: "74-86-7A-FC-38-07",
        ativo: "001-0165",
        setor: "Bobina",
        responsavel: "Anthony",
        ultimaLimpeza: "",
        proximaLimpeza: "2026-10-21",
        preventiva: "21/10",
        statusPlanilha: "Pendente",
        problemaEncontrado: "",
        solucaoAcao: "",
        observacoes: ""
    },
    {
        id: "pc-062",
        nome: "Clodoaldo",
        ip: "192.168.5.33",
        mac: "34-E8-D7-FC-19-02",
        ativo: "001-0166",
        setor: "Montagem",
        responsavel: "Clodoaldo",
        ultimaLimpeza: "",
        proximaLimpeza: "2026-10-22",
        preventiva: "22/10",
        statusPlanilha: "Pendente",
        problemaEncontrado: "",
        solucaoAcao: "",
        observacoes: ""
    },
    {
        id: "pc-063",
        nome: "Gustavo",
        ip: "192.168.5.22",
        mac: "78-2B-CB-C8-77-FD",
        ativo: "001-0167",
        setor: "Qualidade",
        responsavel: "Gustavo",
        ultimaLimpeza: "",
        proximaLimpeza: "2026-10-22",
        preventiva: "22/10",
        statusPlanilha: "Pendente",
        problemaEncontrado: "",
        solucaoAcao: "",
        observacoes: ""
    },
    {
        id: "pc-064",
        nome: "Richard/Rafael",
        ip: "192.168.5.202",
        mac: "90-81-10-F6-72-18",
        ativo: "001-0168",
        setor: "Qualidade",
        responsavel: "Richard/Rafael",
        ultimaLimpeza: "",
        proximaLimpeza: "2026-10-22",
        preventiva: "22/10",
        statusPlanilha: "Pendente",
        problemaEncontrado: "",
        solucaoAcao: "",
        observacoes: ""
    },
    {
        id: "pc-065",
        nome: "Gabriele",
        ip: "192.168.5.160",
        mac: "74-86-7A-F7-10-02",
        ativo: "001-0169",
        setor: "Motor de Partida",
        responsavel: "Gabriele",
        ultimaLimpeza: "",
        proximaLimpeza: "2026-10-20",
        preventiva: "20/10",
        statusPlanilha: "Pendente",
        problemaEncontrado: "",
        solucaoAcao: "",
        observacoes: ""
    },
    {
        id: "pc-066",
        nome: "Junior",
        ip: "192.168.5.101",
        mac: "74-86-7A-FD-38-88",
        ativo: "001-0170",
        setor: "Usinagem",
        responsavel: "Junior",
        ultimaLimpeza: "",
        proximaLimpeza: "2026-10-22",
        preventiva: "22/10",
        statusPlanilha: "Pendente",
        problemaEncontrado: "",
        solucaoAcao: "",
        observacoes: ""
    },
    {
        id: "pc-067",
        nome: "Consulta",
        ip: "192.168.5.63",
        mac: "34-D0-A9-01-F6-22",
        ativo: "001-0171",
        setor: "Usinagem",
        responsavel: "Consulta",
        ultimaLimpeza: "",
        proximaLimpeza: "2026-10-23",
        preventiva: "23/10",
        statusPlanilha: "Pendente",
        problemaEncontrado: "",
        solucaoAcao: "",
        observacoes: ""
    },
    {
        id: "pc-068",
        nome: "Jhonny",
        ip: "192.168.5.160",
        mac: "D4-8B-54-CE-D0-4A",
        ativo: "001-0172",
        setor: "Bobina",
        responsavel: "Jhonny",
        ultimaLimpeza: "",
        proximaLimpeza: "2026-10-23",
        preventiva: "23/10",
        statusPlanilha: "Pendente",
        problemaEncontrado: "",
        solucaoAcao: "",
        observacoes: ""
    },
    {
        id: "pc-069",
        nome: "Ana Caroline",
        ip: "192.168.5.111",
        mac: "F0-4D-A2-E6-10-F1",
        ativo: "001-0173",
        setor: "Comercial",
        responsavel: "Ana Caroline",
        ultimaLimpeza: "",
        proximaLimpeza: "2026-10-23",
        preventiva: "23/10",
        statusPlanilha: "Pendente",
        problemaEncontrado: "",
        solucaoAcao: "",
        observacoes: ""
    },
    {
        id: "pc-070",
        nome: "Aline",
        ip: "192.168.5.80",
        mac: "90-81-1C-F7-8B-46",
        ativo: "001-0174",
        setor: "Comercial",
        responsavel: "Aline",
        ultimaLimpeza: "",
        proximaLimpeza: "2026-10-26",
        preventiva: "26/10",
        statusPlanilha: "Pendente",
        problemaEncontrado: "",
        solucaoAcao: "",
        observacoes: ""
    },
    {
        id: "pc-071",
        nome: "Leila",
        ip: "192.168.5.178",
        mac: "78-2B-CB-8C-E9-AB",
        ativo: "001-0175",
        setor: "Comercial",
        responsavel: "Leila",
        ultimaLimpeza: "",
        proximaLimpeza: "2026-10-26",
        preventiva: "26/10",
        statusPlanilha: "Pendente",
        problemaEncontrado: "",
        solucaoAcao: "",
        observacoes: ""
    },
    {
        id: "pc-072",
        nome: "Lívia",
        ip: "192.168.5.130",
        mac: "F0-4D-A2-E7-57-83",
        ativo: "001-0176",
        setor: "Comercial",
        responsavel: "Lívia",
        ultimaLimpeza: "",
        proximaLimpeza: "2026-10-26",
        preventiva: "26/10",
        statusPlanilha: "Pendente",
        problemaEncontrado: "",
        solucaoAcao: "",
        observacoes: ""
    },
    {
        id: "pc-073",
        nome: "Pintura",
        ip: "192.168.5.19",
        mac: "7C-83-34-83-83-68",
        ativo: "001-0176",
        setor: "Pintura",
        responsavel: "Pintura",
        ultimaLimpeza: "",
        proximaLimpeza: "2026-10-26",
        preventiva: "26/10",
        statusPlanilha: "Pendente",
        problemaEncontrado: "",
        solucaoAcao: "",
        observacoes: ""
    },
    {
        id: "pc-074",
        nome: "Reginaldo",
        ip: "192.168.5.62",
        mac: "78-2B-CB-EB-E1-55",
        ativo: "001-0177",
        setor: "Expedição Moya",
        responsavel: "Reginaldo",
        ultimaLimpeza: "",
        proximaLimpeza: "2026-10-28",
        preventiva: "28/10",
        statusPlanilha: "Pendente",
        problemaEncontrado: "",
        solucaoAcao: "",
        observacoes: ""
    },
    {
        id: "pc-075",
        nome: "Guilherme",
        ip: "192.168.5.25",
        mac: "78-2B-CB-EC-77-4A",
        ativo: "001-0178",
        setor: "Expedição Moya",
        responsavel: "Guilherme",
        ultimaLimpeza: "",
        proximaLimpeza: "2026-10-28",
        preventiva: "28/10",
        statusPlanilha: "Pendente",
        problemaEncontrado: "",
        solucaoAcao: "",
        observacoes: ""
    }
];

const initialHistory = [];